apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  {{- with .Values.service }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .target_port }}
    protocol: TCP
  type: {{ .type }}
  {{- end }}
